server:
  port: 8588

spring:
  application:
    name: BulkHeadTester

resilience4j:
  bulkhead:
    instances:
      bulkhead:
        maxConcurrentCalls: 2
        maxWaitDuration: 5s

internal:
  semaphore:
    limits:
      - name: MASTERCARD
        permit: 2
        time-out-ms: 2_000
      - name: VISA
        permit: 1
        time-out-ms: 60_000
      - name: ONLINE
        permit: 4
        time-out-ms: 30_000